{
    "TC1027": {
        "name": "Business Programming",
        "udc": 1,
        "periods": ["P2"],
        "semester": "1",
        "hours": 20,
    },
    "TC1028": {
        "name": "Computational Thinking for Engineering",
        "udc": 2,
        "periods": ["P1", "P2"],
        "semester": "1",
        "hours": 40,
    },
    "TC1029": {
        "name": "Computational Thinking and Programming",
        "udc": 3,
        "periods": ["P1", "P2", "P3"],
        "semester": "1",
        "hours": 60,
    },
    "TC1030": {
        "name": "Object Oriented Programming",
        "udc": 1,
        "periods": ["P3"],
        "semester": "2",
        "hours": 20,
    },
    "TC1031": {
        "name": "Programming of Data Structures and Fundamental Algorithms",
        "udc": 3,
        "periods": ["P1", "P2", "P3"],
        "semester": "3",
        "hours": 60,
    },
    "TC1032": {
        "name": "Modeling of Minimum Systems and Computational Architectures",
        "udc": 1,
        "periods": ["P2"],
        "semester": "3",
        "hours": 20,
    },
    "TC1033": {
        "name": "Object Oriented Computational Thinking",
        "udc": 1,
        "periods": ["P3"],
        "semester": "1",
        "hours": 20,
    },
    "TC1001B": {
        "name": "Principles of Programming for Social Sciences",
        "udc": 3,
        "periods": ["P3"],
        "semester": "1",
        "hours": 60,
    },
    "TC1002B": {
        "name": "Technological Tools for Social Sciences",
        "udc": 3,
        "periods": ["P2"],
        "semester": "4",
        "hours": 60,
    },
    "TC1003B": {
        "name": "Engineering Modeling with Computational Mathematics",
        "udc": 3,
        "periods": ["P1"],
        "semester": "2",
        "hours": 60,
    },
    "TC1004B": {
        "name": "Implementation of Internet of Things",
        "udc": 6,
        "periods": ["P2", "P3"],
        "semester": "3",
        "hours": 120,
    },
    "TC2037": {
        "name": "Implementation of Computational Methods",
        "udc": 3,
        "periods": ["P1", "P2", "P3"],
        "semester": "4",
        "hours": 60,
    },
    "TC2038": {
        "name": "Analysis and Design of Advanced Algorithms",
        "udc": 3,
        "periods": ["P1", "P2", "P3"],
        "semester": "5",
        "hours": 60,
    },
    "TC2005B": {
        "name": "Software Construction and Decision Making",
        "udc": 8,
        "periods": ["P1", "P2"],
        "semester": "4",
        "hours": 160,
    },
    "TC2006B": {
        "name": "Interconnection of Devices",
        "udc": 4,
        "periods": ["P3"],
        "semester": "4",
        "hours": 80,
    },
    "TC2007B": {
        "name": "Integration of Computer Security in Networks and Software Systems",
        "udc": 8,
        "periods": ["P1", "P2"],
        "semester": "5",
        "hours": 160,
    },
    "TC2008B": {
        "name": "Modeling of Multi-agent Systems with Computational Graphics",
        "udc": 4,
        "periods": ["P3"],
        "semester": "5",
        "hours": 80,
    },
    "TC3001B": {
        "name": "Software Development",
        "udc": 18,
        "periods": ["P1", "P2", "P3"],
        "semester": "6",
        "hours": 360,
    },
    "TC3002B": {
        "name": "Development of Advanced Applications of Computational Sciences",
        "udc": 6,
        "periods": ["P2"],
        "semester": "8",
        "hours": 120,
    },
    "TC3003B": {
        "name": "Implementation of Wide Area Networks and Distributed Services",
        "udc": 6,
        "periods": ["P3"],
        "semester": "8",
        "hours": 120,
    },
    "TC3004B": {
        "name": "Software Systems Planning",
        "udc": 6,
        "periods": ["P1"],
        "semester": "8",
        "hours": 120,
    },
    "TC3005B": {
        "name": "Development and Implementation of Software Systems",
        "udc": 12,
        "periods": ["P2", "P3"],
        "semester": "8",
        "hours": 240,
    },
    "TI1015": {
        "name": "Software Requirements Analysis",
        "udc": 1,
        "periods": ["P3"],
        "semester": "3",
        "hours": 20,
    },
    "TI3001C": {
        "name": "Data Analytics and Artificial Intelligence Tools I",
        "udc": 7,
        "periods": ["P1", "P2", "P3"],
        "semester": "7",
        "hours": 140,
    },
    "TI3002C": {
        "name": "Data Analytics and Artificial Intelligence Tools II",
        "udc": 13,
        "periods": ["P1", "P2", "P3"],
        "semester": "7",
        "hours": 260,
    },
    "TI3005B": {
        "name": "Digital Transformation of Civil Society Organizations",
        "udc": 6,
        "periods": ["P1"],
        "semester": "8",
        "hours": 120,
    },
}
